# Generated by Django 4.2.7 on 2023-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=5)),
            ],
        ),
    ]
